config/routes.rb
Oliver::Application.routes.draw do
  resources :visualisations

  devise_for :users

  resources :pulse_applications

  resources :data_sources do
    resources :comments
    resources :data_sets
  end
  
  resources :platforms
  
  resources :tools

  root :to => "application#index"
end

app/models/data_set.rb
require 'net/http'

class DataSet
  include Mongoid::Document
  belongs_to :data_source

  field :name, :type => String
  field :uri, :type => String
  field :description, :type => String
  field :raw_data, :type => String
  field :transform_script, :type => String
  field :data, :type => Array

  def refresh_data(host_adaptor)
    u             = URI::parse(URI.escape(uri))
    self.raw_data = host_adaptor.get(u)
  end

  def transform(mapping)
    dt        = DataTransformation.new(mapping)
    self.data = []
    dt.transform(self.raw_data, self.data)
  end
end

app/controllers/data_sets_controller.rb
class DataSetsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @data_source = DataSource.find(params[:data_source_id])
    @data_sets   = @data_source.data_sets

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @data_sets }
    end
  end

  def show
    @data_source = DataSource.find(params[:data_source_id])
    @data_set    = DataSet.find(params[:id])

    respond_to do |format|
      format.html
      format.xml { render :xml => @data_set }
    end
  end

  def new
    @data_source = DataSource.find(params[:data_source_id])
    @data_set    = @data_source.data_sets.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @data_set }
    end
  end

  def edit
    @data_source = DataSource.find(params[:data_source_id])
    @data_set    = DataSet.find(params[:id])
  end

  def refresh_and_transform_data
    if @data_set.uri
      @data_set.refresh_data(HostAdaptor.new)
      @data_set.transform(@data_set.transform_script)
    end
  end

  def create
    @data_source = DataSource.find(params[:data_source_id])
    @data_set    = @data_source.data_sets.create!(params[:data_set])

    refresh_and_transform_data()

    respond_to do |format|
      if @data_set.save
        format.html { redirect_to(data_source_data_set_path(@data_source, @data_set), :notice => 'Data set was successfully created.') }
        format.xml { render :xml => @data_set, :status => :created, :location => @data_set }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @data_set.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @data_source = DataSource.find(params[:data_source_id])
    @data_set    = DataSet.find(params[:id])

    respond_to do |format|
      if @data_set.update_attributes(params[:data_set])

        refresh_and_transform_data()

        @data_set.save

        format.html { redirect_to(data_source_data_set_path(@data_source, @data_set), :notice => 'Data set was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @data_set.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @data_source = DataSource.find(params[:data_source_id])
    @data_set    = DataSet.find(params[:id])
    @data_set.destroy

    respond_to do |format|
      format.html { redirect_to(data_source_data_sets_url(@data_source)) }
      format.xml { head :ok }
    end
  end
end

app/helpers/data_sets_helper.rb
module DataSetsHelper
end

app/views/data_sets/_form.html.haml
= form_for [@data_source, @data_set] do |f|
  - if @data_set.errors.any?
    #error_explanation
      %h2
        = pluralize(@data_set.errors.count, "error")
        prohibited this data_set from being saved:
      %ul
        - @data_set.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :uri
    %br/
    = f.text_field :uri
  .field
    = f.label :transform_script
    %br/
    = f.text_area :transform_script
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/data_sets/edit.html.haml
#page-navigation
  %ul
    %li= icon_link_to :home, data_source_path(@data_source)
    %li= icon_link_to :document, data_source_data_set_path(@data_source, @data_set)


%h1 Editing data_set
= render 'form'

app/views/data_sets/index.html.haml
%h1 Listing data_sets
%table
  %tr
    %th Name
    %th Uri
    %th Description
    %th
    %th
    %th
  - @data_sets.each do |data_set|
    %tr
      %td= data_set.name
      %td= data_set.uri
      %td= data_set.description
      %td= link_to 'Show', data_source_data_set_path(@data_source, data_set)
      %td= link_to 'Edit', edit_data_source_data_set_path(@data_source, data_set)
      %td= link_to 'Destroy', data_source_data_set_path(@data_source, data_set), :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Data set', new_data_source_data_set_path(@data_source)

app/views/data_sets/new.html.haml
%h1 New data_set
= render 'form'
= link_to 'Back', data_source_data_sets_path(@data_source)

app/views/data_sets/show.html.haml
%p#notice= notice

#page-navigation
  %ul
    %li= icon_link_to :home, data_source_path(@data_source)
    %li= icon_link_to :pencil, edit_data_source_data_set_path(@data_source, @data_set)

.data-set
  %p
    %b Name:
    = @data_set.name
  %p
    %b Uri:
    = @data_set.uri
  %p
    %b Description:
    = @data_set.description
  %p
    %b Transform script
  %pre.prettyprint.lang-rb
    = @data_set.transform_script

  %p Tansformed Data
  - if @data_set.data && @data_set.data.size > 0
    %table
      %tr
        - @data_set.data[0].keys.each do |key|
          %th= key
      - @data_set.data.each do |e|
        %tr
          - @data_set.data[0].keys.each do |key|
            %td= e[key]

  %p
    Raw Data
  %pre.prettyprint.lang-xml
    = format_raw_data(@data_set.raw_data)

%script
  $(document).ready(function() {prettyPrint();});