config/routes.rb
Oliver::Application.routes.draw do
  resources :visualisations

  devise_for :users

  resources :pulse_applications

  resources :data_sources do
    resources :comments
    resources :data_sets
  end
  
  resources :platforms
  
  resources :tools

  root :to => "application#index"
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController

  # GET /platform
  # GET /platform.xml
  def index
    @platforms = Platform.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @platform }
    end
  end

  # GET /platform/1
  # GET /platform/1.xml
  def show
    @platform = Platform.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @platform }
    end
  end

  # GET /platform/new
  # GET /platform/new.xml
  def new
    @platform = Platform.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @platform }
    end
  end

  # GET /platform/1/edit
  def edit
    @platform = Platform.find(params[:id])
  end

  # POST /platform
  # POST /platform.xml
  def create
    @platform = Platform.new(params[:platform])

    respond_to do |format|
      if @platform.save
        format.html { redirect_to(@platform, :notice => 'Data source was successfully created.') }
        format.xml  { render :xml => @platform, :status => :created, :location => @platform }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @platform.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /platform/1
  # PUT /platform/1.xml
  def update
    @platform = Platform.find(params[:id])

    respond_to do |format|
      if @platform.update_attributes(params[:platform])
        format.html { redirect_to(@platform, :notice => 'Data source was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @platform.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /platform/1
  # DELETE /platform/1.xml
  def destroy
    @platform = Platform.find(params[:id])
    @platform.destroy

    respond_to do |format|
      format.html { redirect_to(platform_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/views/platforms/_form.html.haml
= form_for(@platform) do |f|
  - if @platform.errors.any?
    #error_explanation
      %h2
        = pluralize(@platform.errors.count, "error")
        prohibited this platform from being saved:
      %ul
        - @platform.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :url
    %br/
    = f.text_field :url
  .field
    = f.label :affiliation
    %br/
    = f.text_field :affiliation
  .field
    = f.label :primarypurpose
    %br/
    = f.text_field :primarypurpose
  .field
    = f.label :bandwidthcapability
    %br/
    = f.text_field :bandwidth
  .field
    = f.label :serverlatitude
    %br/
    = f.text_field :latitude
  .field
    = f.label :serverlongitude
    %br/
    = f.text_field :longitude

  .actions
    = f.submit

app/views/platforms/edit.html.haml
%h1 Editing platform
= render 'form'
= link_to 'Show', @platform
|
\#{link_to 'Back', platforms_path}

app/views/platforms/index.html.haml
%h1 Connected Platforms
%table
  %tr
    %th Name
    %th Url
    %th Primary purpose
    %th Actions
    %th
    %th
  - @platforms.each do |platform|
    %tr
      %td= platform.name
      %td= platform.url
      %td= platform.primarypurpose
      %td= link_to 'Show', platform
      %td= link_to 'Edit', edit_platform_path(platform)
      %td= link_to 'Destroy', platform, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New platform', new_platform_path

app/views/platforms/new.html.haml
%h1 Register Platform
= render 'form'
= link_to 'Back', platforms_path

app/views/platforms/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @platform.name
%p
  %b Url:
  = @platform.url
= link_to 'Edit', edit_platform_path(@platform)
|
\#{link_to 'Back', platforms_path}