config/routes.rb
Oliver::Application.routes.draw do
  resources :visualisations

  devise_for :users

  resources :pulse_applications

  resources :data_sources do
    resources :comments
    resources :data_sets
  end
  
  resources :platforms
  
  resources :tools

  root :to => "application#index"
end

app/models/data_source.rb
# A DataSource represents an organisation that makes data available to others.
# A data source contains a number of DataSets that have ben used for analysis.
#
class DataSource
  include Mongoid::Document

  field :name
  field :uri
  field :api_key
  field :source
  field :client_adaptor
  field :catalogue, :type => Array
  field :raw_catalogue
  field :catalogue_script
  field :generatingagency
  field :dataformat
  field :acquisitondate
  field :contributoruid
  field :affiliation
  field :whocanview
  field :whocanedit
  field :whocanadmit
  field :dataquality
  field :datastandards
  field :metatdatalink
  field :apilink

  validates_presence_of :name, :on => :create, :message => "A unique data source name is required"

  has_many :comments
  has_many :data_sets

  def test
    adaptor = eval(client_adaptor)

    adaptor.data_sets
  end

  def refresh_catalogue(host_adaptor)
    u                  = URI::parse(URI.escape(uri))
    self.raw_catalogue = host_adaptor.get(u)
  end

  def build_data_sets(script)
    dsb = DataSetBuilder.new(script)

    dsb.build(self)
  end

end

app/controllers/data_sources_controller.rb
class DataSourcesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @data_sources = DataSource.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @data_sources }
    end
  end

  def show
    @data_source = DataSource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @data_source }
    end
  end

  def new
    @data_source = DataSource.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @data_source }
    end
  end

  def edit
    @data_source = DataSource.find(params[:id])
  end

  def create
    @data_source = DataSource.new(params[:data_source])

    respond_to do |format|
      if @data_source.save
        format.html { redirect_to(@data_source, :notice => 'Data source was successfully created.') }
        format.xml { render :xml => @data_source, :status => :created, :location => @data_source }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @data_source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /data_sources/1
  # PUT /data_sources/1.xml
  def update
    @data_source = DataSource.find(params[:id])

    respond_to do |format|
      if @data_source.update_attributes(params[:data_source])
        format.html { redirect_to(@data_source, :notice => 'Data source was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @data_source.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /data_sources/1
  # DELETE /data_sources/1.xml
  def destroy
    @data_source = DataSource.find(params[:id])
    @data_source.destroy

    respond_to do |format|
      format.html { redirect_to(data_sources_url) }
      format.xml { head :ok }
    end
  end
end

app/helpers/data_sources_helper.rb
module DataSourcesHelper
end

app/views/data_sources/_comments.html.haml
%h2 Comments
- @data_source.comments.each do |comment|
  .comment
    .name
      = image_tag avatar_url(comment.user)
      = comment.user
    .content= comment.content
= form_for [@data_source, Comment.new] do |f|
  %fieldset
    %legend New Comment
    %br/
    = f.label :content
    %br/
    = f.text_area :content, :rows => 4
    %br/
    = f.submit

app/views/data_sources/_data_sets.html.haml
.navigation
  %ul
    %li= icon_link_to :plus, new_data_source_data_set_path(@data_source)

%h2 Data Sets
- if @data_source.data_sets.size() > 0
  %table
    %tr
      %th Name
      %th URI
      %th
    - @data_source.data_sets.each do |ds|
      %tr
        %td= ds.name
        %td= ds.uri
        %td
          = icon_link_to :document, data_source_data_set_path(@data_source, ds)
          = icon_link_to :pencil, edit_data_source_data_set_path(@data_source, ds)
          = link_to tag(:span, {:class => 'ui-icon ui-icon-trash'}), data_source_data_set_path(@data_source, ds), :confirm => 'Are you sure?', :method => :delete

- else
  (No data sets defined yet)

app/views/data_sources/_description.html.haml
%h2 Description
%table
  %tr
    %td Name
    %td= @data_source.name
  -#%tr
  -#  %td Source
  -#  %td= @data_source.source
  %tr
    %td Uri
    %td= @data_source.uri
  -#%tr
  -#  %td Api Key
  -#  %td= @data_source.api_key
  -#%tr
  -#  %td Client Adaptor
  -#  %td
  -#    = @data_source.client_adaptor
  -#    &nbsp;
  -#    = link_to "test", test_data_source_path(@data_source)
  -#%tr
  -#  %td Generating Agency
  -#  %td= @data_source.generatingagency
  -#%tr
  -#  %td Data Format
  -#  %td= @data_source.dataformat
  -#%tr
  -#  %td Acquisition Date
  -#  %td= @data_source.acquisitondate
  -#%tr
  -#  %td Contributor UID
  -#  %td= @data_source.contributoruid
  -#%tr
  -#  %td Affiliation
  -#  %td= @data_source.affiliation
  -#%tr
  -#  %td Who Can View
  -#  %td= @data_source.whocanview
  -#%tr
  -#  %td Who Can Edit
  -#  %td= @data_source.whocanedit
  -#%tr
  -#  %td Who can Admit
  -#  %td= @data_source.whocanadmit
  -#%tr
  -#  %td Data Quality
  -#  %td= @data_source.dataquality
  -#%tr
  -#  %td Data Standards
  -#  %td= @data_source.datastandards
  -#%tr
  -#  %td Meta Data Link
  -#  %td= @data_source.metatdatalink
  -#%tr
  -#  %td API Link
  -#  %td= @data_source.apilink

app/views/data_sources/_form.html.haml
= form_for(@data_source) do |f|
  - if @data_source.errors.any?
    #error_explanation
      %h2
        = pluralize(@data_source.errors.count, "error")
        prohibited this data_source from being saved:
      %ul
        - @data_source.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :uri
    %br/
    = f.text_field :uri
  .field
    = f.label :api_key
    %br/
    = f.text_field :api_key
  .field
    = f.label :client_adaptor
    %br/
    = f.text_area :client_adaptor
  .field
    = f.label :source
    %br/
    = f.text_field :source
  .field
    = f.label :generatingagency
    %br/
    = f.text_field :generatingagency
  .field
    = f.label :dataformat
    %br/
    = f.text_field :dataformat
  .field
    = f.label :acquisitondate
    %br/
    = f.text_field :acquisitondate
  .field
    = f.label :contributoruid
    %br/
    = f.text_field :contributoruid
  .field
    = f.label :affiliation
    %br/
    = f.text_field :affiliation
  .field
    = f.label :whocanview
    %br/
    = f.text_field :whocanview
  .field
    = f.label :whocanedit
    %br/
    = f.text_field :whocanedit
  .field
    = f.label :whocanadmit
    %br/
    = f.text_field :whocanadmit
  .field
    = f.label :dataquality
    %br/
    = f.text_field :dataquality
  .field
    = f.label :datastandards
    %br/
    = f.text_field :datastandards
  .field
    = f.label :metatdatalink
    %br/
    = f.text_field :metatdatalink
  .field
    = f.label :apilink
    %br/
    = f.text_field :apilink


  .actions
    = f.submit

app/views/data_sources/edit.html.haml
#page-navigation
  %ul
    %li= icon_link_to :home, data_sources_path
    %li= icon_link_to :document, data_source_path


%h1
  Editing Data Source:
  = @data_source.name
= render 'form'

app/views/data_sources/index.html.haml
%p#notice= notice

#page-navigation
  %ul
    %li= icon_link_to :plusthick, new_data_source_path, :alt => "New Data Source"

%h1 Data Sources
%table
  %tr
    %th Name
    %th Uri
    %th
  - @data_sources.each do |data_source|
    %tr
      %td= data_source.name
      %td= link_to data_source.uri, data_source.uri

      %td
        = icon_link_to :document, data_source_path(data_source)
        = icon_link_to :pencil, edit_data_source_path(data_source)
        = link_to tag(:span, {:class => 'ui-icon ui-icon-trash'}), data_source, :confirm => 'Are you sure?', :method => :delete

app/views/data_sources/new.html.haml
#page-navigation
  %ul
    %li= icon_link_to :home, data_sources_path


%h1 Register Data Source
= render 'form'

app/views/data_sources/show.html.haml
%p#notice= notice

#page-navigation
  %ul
    %li= icon_link_to :home, data_sources_path
    %li= icon_link_to :pencil, edit_data_source_path(@data_source)
    %li= icon_link_to :document, data_source_path

.data-store
  .name
    %ul
      %li
        Data Source:
        = @data_source.name
  .description
    = render :partial => "description", :locals => {:data_source => @data_source}
  -#.dates
  -#  %h2 Dates
  -#  #timeline-data
  -#%table
  -#  %tr
  -#    - time_line = @data_source.time_line
  -#    - time_line.columns.each do |column_title|
  -#      %th=column_title
  -#  - time_line.rows.each do |row|
  -#    %tr
  -#      - row.each_cell do |cell|
  -#        %td= cell
  
  -#  #timeline-chart
  -#  %p Insert timeline chart
  -#.map
  -#  %h2 Map
  -#  #intensity-chart
  -#.assessment
  -#  .tags
  -#    %h2 Tags
  -#  .quality-scores
  -#    %h2 Quality Scores
  .datasets
    =render :partial => "data_sets", :locals => {:data_source => @data_source }
  .comment
    =render :partial => "comments" #, :local => {:data_source => @data_source }

-#= javascript_include_tag 'map-sample'

app/views/data_sources/test.html.haml
#page-navigation
  %ul
    %li= icon_link_to :home, data_sources_path
    %li= icon_link_to :document, data_source_path

.test-result
  %table
    %tr
      %th Name
      %th Organisation
      %th Category
      %th Query URI
    - @test_result.each do |item|
      %tr
        %td= item.name
        %td= item.organisation
        %td= item.category
        %td= link_to "Query", "#{item.query_uri}"