config/routes.rb
Oliver::Application.routes.draw do
  resources :visualisations

  devise_for :users

  resources :pulse_applications

  resources :data_sources do
    resources :comments
    resources :data_sets
  end
  
  resources :platforms
  
  resources :tools

  root :to => "application#index"
end

app/models/pulse_application.rb
class PulseApplication
  include Mongoid::Document

  field :name
  field :description
  field :git_hub_repository
  field :source
  field :url
end

app/controllers/pulse_applications_controller.rb
class PulseApplicationsController < ApplicationController
  before_filter :authenticate_user!, :only => [:edit, :update, :destroy]

  def index
    @pulse_applications = PulseApplication.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @pulse_applications }
    end
  end

  def show
    @pulse_application = PulseApplication.find(params[:id])

#    @repository = github(@pulse_application.url)

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @pulse_application }
    end
  end

  # GET /pulse_applications/new
  # GET /pulse_applications/new.xml
  def new
    @pulse_application = PulseApplication.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @pulse_application }
    end
  end

  # GET /pulse_applications/1/edit
  def edit
    @pulse_application = PulseApplication.find(params[:id])
  end

  # POST /pulse_applications
  # POST /pulse_applications.xml
  def create
    @pulse_application = PulseApplication.new(params[:pulse_application])

    respond_to do |format|
      if @pulse_application.save
        format.html { redirect_to(@pulse_application, :notice => 'Pulse application was successfully created.') }
        format.xml { render :xml => @pulse_application, :status => :created, :location => @pulse_application }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @pulse_application.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pulse_applications/1
  # PUT /pulse_applications/1.xml
  def update
    @pulse_application = PulseApplication.find(params[:id])

    respond_to do |format|
      if @pulse_application.update_attributes(params[:pulse_application])
        format.html { redirect_to(@pulse_application, :notice => 'Pulse application was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @pulse_application.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @pulse_application = PulseApplication.find(params[:id])
    @pulse_application.destroy

    respond_to do |format|
      format.html { redirect_to(pulse_applications_url) }
      format.xml { head :ok }
    end
  end
end

app/helpers/pulse_applications_helper.rb
module PulseApplicationsHelper
end

app/views/pulse_applications/_form.html.haml
= form_for(@pulse_application) do |f|
  - if @pulse_application.errors.any?
    #error_explanation
      %h2
        = pluralize(@pulse_application.errors.count, "error")
        prohibited this pulse_application from being saved:
      %ul
        - @pulse_application.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    %br/
    =f.text_field :name

  .field
    = f.label :description
    %br/
    = f.text_area :description

  .field
    = f.label :git_hub_repository
    (Enter the url for your github repository or username and click the 'Get Info' button)
    %br/
    = f.text_field :git_hub_repository
    %input{:type => "button", :value => "Get Info", :class => "TestLink"}
    .userinfo{:id => "userinfo"}
      %h2 User Info
      %ul{:id => "userinfo"}

      .projectinfo
        %h2 Projects
        %ul{:id=>"projects"}


  .actions
    = f.submit



= javascript_include_tag "enhance.js"

app/views/pulse_applications/edit.html.haml
%h1 Editing pulse_application
= render 'form'
= link_to 'Show', @pulse_application
|
\#{link_to 'Back', pulse_applications_path}

app/views/pulse_applications/index.html.haml
%h1 Listing Pulse Applications
%table
  %tr
    %th Application
    %th
    %th
    %th
    %th
  - @pulse_applications.each do |pulse_application|
    %tr
      %td= pulse_application.name
      %td= pulse_application.description
      %td= pulse_application.url
      %td= link_to 'Show', pulse_application_path(pulse_application)
      %td= link_to 'Edit', edit_pulse_application_path(pulse_application)
      %td= link_to 'Destroy', pulse_application, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Pulse application', new_pulse_application_path

app/views/pulse_applications/new.html.haml
%h1 Register your Global Pulse Application
= render 'form'
= link_to 'Back', pulse_applications_path

app/views/pulse_applications/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_pulse_application_path(@pulse_application)
|
\#{link_to 'Back', pulse_applications_path}